#!/usr/bin/env bash

# Copy-pasted from the Bazel Bash runfiles library v2.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e

kustomize=$1
target_file=$2
shift 2

# Try to find an executable file with a Windows-style name first.
zipper="$(rlocation bazel_tools/tools/zip/zipper/zipper.exe)"
if [ -z "${zipper}" ]; then
  zipper="$(rlocation bazel_tools/tools/zip/zipper/zipper)"
  if [ -z "${zipper}" ]; then
    echo >&2 "Failed to locate the required \"zipper\" tool as a runfile."
    exit 1
  fi
fi

if [ -z "${RUNFILES_MANIFEST_FILE:-}" ]; then
  echo >&2 "The \"RUNFILES_MANIFEST_FILE\" environment variable is not set."
  exit 1
fi
if ! [ -e "${RUNFILES_MANIFEST_FILE}" ]; then
  echo >&2 "The runfiles manifest file "${RUNFILES_MANIFEST_FILE}" does not exist."
  exit 1
fi
if ! [ -f "${RUNFILES_MANIFEST_FILE}" ]; then
  echo >&2 "The runfiles manifest file "${RUNFILES_MANIFEST_FILE}" is not a regular file."
  exit 1
fi

zip_manifest_file="$(mktemp zip-manifest-XXXXXX)"
sed -E -e 's/^([^ ]+) /\1=/' "${RUNFILES_MANIFEST_FILE}" > "${zip_manifest_file}"
runfiles_archive_file="$(mktemp runfiles-archive-XXXXXX)"
"${zipper}" c "${runfiles_archive_file}" "@${zip_manifest_file}"

kustomization_dir="$(mktemp -d kustomization-target-XXXXXX)"
"${zipper}" x "${runfiles_archive_file}" -d "${kustomization_dir}"

if [ "${KUSTOMIZE_RESOURCES__SILENT_ON_SUCCESS:-}" ]; then
    STDERR_CAPTURE=$(mktemp)
fi

_exit() {
    EXIT_CODE=$?

    if [ "${STDERR_CAPTURE:-}" ]; then
        if [ "$EXIT_CODE" != 0 ] || [ -z "${KUSTOMIZE_RESOURCES__SILENT_ON_SUCCESS:-}" ]; then
            cat "$STDERR_CAPTURE" >&2
        fi
        rm "$STDERR_CAPTURE"
    fi

    exit $EXIT_CODE
}

trap _exit EXIT

if [ "${STDERR_CAPTURE:-}" ]; then
  "${kustomize}" build "${kustomization_dir}/$(dirname ${target_file})" "${@}" 2> "$STDERR_CAPTURE"
else
  "${kustomize}" build "${kustomization_dir}/$(dirname ${target_file})" "${@}"
fi
