#!/usr/bin/env bash

# Copy-pasted from the Bazel Bash runfiles library v2.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
  source "$0.runfiles/$f" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e

kustomize=$1
target_file=$2
shift 2

target_runfile_path="$(rlocation ${target_file})"
if [ -z "${target_runfile_path}" ]; then
  echo >&2 "No runfile path available for target file \"${target_file}\"."
  exit 1
fi

if [ "${KUSTOMIZE_RESOURCES__SILENT_ON_SUCCESS:-}" ]; then
    STDERR_CAPTURE=$(mktemp)
fi

_exit() {
    EXIT_CODE=$?

    if [ "${STDERR_CAPTURE:-}" ]; then
        if [ "$EXIT_CODE" != 0 ] || [ -z "${KUSTOMIZE_RESOURCES__SILENT_ON_SUCCESS:-}" ]; then
            cat "$STDERR_CAPTURE" >&2
        fi
        rm "$STDERR_CAPTURE"
    fi

    exit $EXIT_CODE
}

trap _exit EXIT

if [ "${STDERR_CAPTURE:-}" ]; then
  "${kustomize}" build "$(dirname ${target_runfile_path})" "${@}" 2> "$STDERR_CAPTURE"
else
  "${kustomize}" build "$(dirname ${target_runfile_path})" "${@}"
fi
